# Generated by Django 2.0.7 on 2018-08-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180805_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='question',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='student',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
