# Generated by Django 2.0.7 on 2018-08-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180805_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emailid', models.EmailField(max_length=50)),
                ('rollno', models.IntegerField(max_length=12)),
                ('branch', models.CharField(max_length=5)),
                ('year', models.IntegerField(max_length=2)),
                ('contact_no', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='student1',
        ),
    ]
