# Generated by Django 2.0.7 on 2018-08-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180805_1626'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
