# Generated by Django 2.0.7 on 2018-08-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='question',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='student',
        ),
        migrations.AddField(
            model_name='vote',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='student_id',
            field=models.IntegerField(default=0),
        ),
    ]
