# Generated by Django 2.0.7 on 2018-08-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180805_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='contact_no',
        ),
    ]
