# Generated by Django 2.0.7 on 2018-08-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='question_id',
        ),
    ]
