# Generated by Django 2.0.7 on 2018-08-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_vote_ques_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='ques_id',
        ),
    ]
