# Generated by Django 2.0.7 on 2018-08-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_vote_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='question',
            new_name='questio',
        ),
    ]
