# Generated by Django 2.0.7 on 2018-08-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180805_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='question',
        ),
    ]
