# Generated by Django 2.0.7 on 2018-08-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_svote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='svote',
            name='question',
        ),
        migrations.RemoveField(
            model_name='svote',
            name='student',
        ),
    ]
