# Generated by Django 2.0.7 on 2018-08-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180805_1905'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sVote',
            new_name='Vote',
        ),
    ]
