# Generated by Django 2.0.7 on 2018-08-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20180805_1907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
