# Generated by Django 2.0.7 on 2018-08-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20180805_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
