# Generated by Django 2.0.7 on 2018-08-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20180805_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vo',
            name='vote',
            field=models.IntegerField(),
        ),
    ]
